name: 'Creds'

on:
  push:
    branches:
    - "production_branch"
    - "dev_branch"  

# env:
#   AWS_ACCESS_KEY_ID: ${{ secrets.PRODUNCTION_AWS_ACCESS_KEY_ID }}
#   AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUNCTION_AWS_SECRET_ACCESS_KEY }}
#   AWS_ACCESS_KEY_ID: 'Hello_production_access_key'
#   AWS_SECRET_ACCESS_KEY: 'Hello_production_secret_key'
#   AWS_REGION: "ap-southeast-1"    
  
jobs:
  Enviro: 
    name: 'Environement variable'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checking branch
        id: branch_checker
        run: |
          if [ "${{ github.ref }}" = "refs/heads/production_branch" ]; then
            echo "::set-output name=AWS_ACCESS_KEY_ID::${{secrets.AWS_ACCESS_KEY_ID}}"
            echo "::set-output name=AWS_SECRET_ACCESS_KEY::${{secrets.AWS_SECRET_ACCESS_KEY}}"
          else
            echo "::set-output name=AWS_ACCESS_KEY_ID::${{secrets.AWS_ACCESS_KEY_ID}}"
            echo "::set-output name=AWS_SECRET_ACCESS_KEY::${{secrets.AWS_SECRET_ACCESS_KEY}}"
          fi         
        
    outputs:
      AWS_ACCESS_KEY_ID: ${{steps.branch_checker.outputs.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{steps.branch_checker.outputs.AWS_SECRET_ACCESS_KEY}}
    
  Creating_resources:
    name: 'resources'
    runs-on: ubuntu-latest
    environment: production
    needs: [Enviro]
    env: 
      AWS_ACCESS_KEY_ID: ${{needs.Enviro.outputs.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{needs.Enviro.outputs.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: "ap-southeast-1"
    
    defaults:
      run:
        shell: bash

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Echoing
      run: |
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY
